on:
  push:
    branches:
      - develop

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    strategy:
      matrix:
        server:
          - name: 'orrvil01dev Server'
            url: 'jdbc:sqlserver://c60dataorrvil01dev.database.windows.net:1433;database=analytics;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30'
            DB_USERNAME: ${{DB_USERNAME_ORRVIL01DEV}}
            DB_PASSWORD: ${{DB_PASSWORD_ORRVIL01DEV}}
          - name: 'orrvil01test Server2'
            url: 'jdbc:sqlserver://c60dataorrvil01test.database.windows.net:1433;database=analytics;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30'
            DB_USERNAME: ${DB_USERNAME_ORRVIL01TEST}
            DB_PASSWORD: ${{DB_PASSWORD_ORRVIL01TEST}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Liquibase Action
        uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'Liquibase/changelogs'
          changeLogFile: 'MinorChangeLog.xml'
          username: ${{ matrix.server.DB_USERNAME }}
          password: ${{ matrix.server.DB_PASSWORD}}
          url: ${{ matrix.server.url }}
