
on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    strategy:
      matrix:
        server:
          - name: 'Server1'
            url: '//jdbc:sqlserver://c60dataorrvil01dev.database.windows.net:1433;database=analytics;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30'
            username: 'eFQdEzFpfItrtpPm'
            password: '<rpbuMm8dK7=zgvQcSOT9Ceg(mu:Tx:ZV#o=>Sm['
          - name: 'Server2'
            url: '//jdbc:sqlserver://c60dataorrvil01dev.database.windows.net:1433;database=opportunityActions;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30'
            username: 'eFQdEzFpfItrtpPm'
            password: '<rpbuMm8dK7=zgvQcSOT9Ceg(mu:Tx:ZV#o=>Sm['

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Liquibase Action
        uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'samplechangelog.h2.sql'
          username: ${{ matrix.server.username }}
          password: ${{ matrix.server.password }}
          url: ${{ matrix.server.url }}


#on: [push]

#jobs:
#  test-liquibase-action:
#    runs-on: ubuntu-latest
#    name: Test Liquibase Action

#    steps:
#      - uses: actions/checkout@v2
#      - uses: liquibase/liquibase-github-action@v2
#        with:
#          operation: 'update'
#          classpath: 'example/changelogs'
#          changeLogFile: 'samplechangelog.h2.sql'
#          username: 'eFQdEzFpfItrtpPm'
#          password: '<rpbuMm8dK7=zgvQcSOT9Ceg(mu:Tx:ZV#o=>Sm['
#          url: 'jdbc:sqlserver://c60dataorrvil01dev.database.windows.net:1433;database=analytics;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30'

        
