# This is a basic workflow to help you get started with Actions

name: Liquibase_Gradle_GitHub-Hosted

on: [push]

# For more control over when the action will run, comment out (or delete) the above and trigger the workflow on master-branch push or pull request
# by uncommenting the appropriate section below.
# on:
# workflow_dispatch:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "LBJobCLI and LBJobMaven"
  LBJobGradle:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: RunLiquibaseGradleCommands
        uses: actions/checkout@v2
      - run: | 
          cd extra/Gradle_h2
          pwd
          gradle build
          gradle updateSQL
          gradle update
          
          #Uncomment the line below to save changes.  Also, see environment variables under "env" assign variables accordingly
          #git config --global user.email $user.email; git config --global user.name $user.name; git config pull.rebase false; git add .; git commit -m $"message"; git push -u origin $branch
          
        env:
            user.email: "<email>"
            user.name: "<username>"
            message: "<enter commit message>"
            branch: "<git branch name>"
